name: release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: setup env
        run: |
          echo "GOPATH=${{ github.workspace }}" >> $GITHUB_ENV
        shell: bash
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: src/github.com/${{ github.repository }}
      - name: deps
        run: |
          cd $GOPATH/src/github.com/${{ github.repository }}
          make install-tools
        shell: bash
      - name: release
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        run: |
          cd $GOPATH/src/github.com/${{ github.repository }}
          make crossbuild upload
        shell: bash
